### ISSUE TITLE
希望可以增加镜像站

### ISSUE THREAD

**Issue by CreeperAWA** [PBH-BTN/pbh-docs#4]
GitHub Pages 在某些特殊网络环境下还是太慢了，甚至无法访问，所以我希望可以增加一个镜像站或直接使用这个方案存放文档
例如使用 CloudFlare Pages 经过我的测试，该方案访问速度非常快 网址：[pbh-docs.pages.dev](pbh-docs.pages.dev)
补充：该镜像站由我手动同步，因为baseUrl需要修改，GitHub Actions 可能可以自动操作，但是我还没有尝试
如果文档访问次数不是很多，该方案并不需要额外付费，CloudFlare 的免费计划将 Workers 和 Pages Functions 的请求合并。对 Pages 上的静态资产的请求将继续免费，且无数量限制。（详见 [https://developers.cloudflare.com/pages/functions/pricing](https://developers.cloudflare.com/pages/functions/pricing)）

**Comment by Ghost-chu** [comment]
感谢您的建议！

我们通过 CloudFlare Pages 创建了新的镜像站，欢迎尝试！

https://docs.pbh-btn.com
